package apps.stockexchange.beans;

public enum StockType {

	CERTIFICATO_AZIONARIO,
	CERTIFICATO_OBBLIGAZIONARIO_DEBITO_SOVRANO,
	CERTIFICATO_OBBLIGAZIONARIO_PRIVATO,
	TITOLO_DERIVATO,
	OPZIONE,
	QUOTA_FONDO_INVESTIMENTO,
	EQUITY_SWAP;
	
}
